<?php
$row = $res->fetch_array();
$canary->value = $fiber;
$bert = "file://" . __DIR__ . "/bug41033.pem";
$bug_gh16013_callback_struct->return_int32 = function($val) use($ffi) {
    $cdata = $ffi->new('int32_t');
    $cdata->cdata = $val;
    return $cdata;
};
$filename = __DIR__ . '/_fromUri_custom_constructor.xml';
$thisdir = __DIR__;
$prefix . "フォルダ";

mkdir($prefi;
$create = sprintf('%s)', substr($create, 0, -2));
$rows = array();
$heredoc_needle = <<<EOD
^^&*(
EOD;
$cfg['names'] = ['cccc', 'aaaa', 'eeee', 'dddd', 'bbbb'];
$closure1 = new_closure_gen();
$attrs = [ PDO::ATTR_PREFETCH => 0 ];
$foo = new Foo;
$max = 0x66666666;
$empty = "";
$fiber = $iterable = $canary = null;
printf("%-10s => %s\n", $test, date(DATE_ISO8601, $t));
var_dump($output);
$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
imageline($im, 150, 150, 650, 150, IMG_COLOR_STYLED);
var_dump(($bug_gh16013_callback_struct->return_int32)(-100000));
var_dump(soundex("Euler"));
$o->foo();
printf("%.1f%% vs. %.1f%%\n", 100. * $halves[0] / $total, 100. * $halves[1] / $total);
$server->handle($HTTP_RAW_POST_DATA);
var_dump ( rtrim("rtrim test   " , "") );
->appendChild($node);

pr;
var_dump($sends1);
curl_setopt($ch, CURLOPT_VERBOSE, true);
var_dump(substr_compare('/', '/asd', 0, 4));
php_cli_server_start($code, null, $args);
$list->rewind();
mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
var_dump($obj);
var_dump(class_exists("TestClass", true));
$tester->expectLogNotice($userMessage, 'aaaa');
printf("printf test 28:%2\$02d %1\$2d\n", 1, 2);
var_dump($value);
var_dump(strncmp("test ", "e", -1));
test('<?php echo "1";//22');
var_dump($create);
printf("[010] Found unexpected field '%s'\n", $field->name);
stream_get_line($fp, 1024*1024*2, "aaaa");
var_dump(($bug_gh16013_callback_struct->return_float)(12.34));
var_dump(filesize($tmpFileIn) === strlen($originalEnvelopeData));
var_dump(gzread($h, 0));
printf("[%03d] UPDATE failed, [%d] %s\n",
                $offset, mysqli_errno($link), mysqli_error($link));
var_dump(sha1_file(__DIR__ . DIRECTORY_SEPARATOR . 'gh10370_003' . DIRECTORY_SEPARATOR . 'testfile'));
var_dump(file_get_contents(__DIR__ . "/bug69279.txt"));
var_dump($i);
printf("printf test 15:%b\n", 170);
var_dump(sprintf("%%", 1.23456789e10));
test("http://t[est@::1]");
fclose($this->stream);
var_dump($output);
debug_print_backtrace();
ith_cp($d1, 65001);

touch("$d0\\;
$stmt->execute([ 32 ]);
ob_start();
var_dump($db->getAttribute(PDO::DBLIB_ATTR_SKIP_EMPTY_ROWSETS));
$f->resume();
chdir($oldcwd);
$tester->request(connKeepAlive: true)->expectBody('1');
$datefmt->parse('abc');
set_error_handler(function (int $errno, string $errstr, ?string $errfile = null, ?int $errline = null) {
    throw new \ErrorException($errstr, 0, $errno, $errfile, $errline);
});
var_dump( array_udiff($array1, $value, $data_comp_func) );
var_dump($oIntlDateFormatter->getTimeZone()->getID());
var_dump($temp_array);
var_dump( end($test_array) );
var_dump(soundex("Lloyd"));
var_dump($r[$ref]);
$db->setNoticeCallback($callback);
var_dump($array->offsetExists('key'));
var_dump( array_unshift($temp_array, $var, "hello", 'world') );
var_dump($stmt->fetchAll());
printf("Content-Type Default NOK %s" . PHP_EOL, $headers);
var_dump(sprintf("%030.-15s", $tempstring));
test_image_equals_file(__DIR__ . '/bug43475.png', $im);
$prefixed->setAttributeNS("http://www.w3.org/2000/xmlns/", "xmlns:a", "urn:another");
var_dump(openssl_x509_checkpurpose($sert, X509_PURPOSE_CRL_SIGN));
test('Ghost', $obj);
dumpNodeList($dom->getElementsByTagName("HTML"));
var_dump(getimagesize(__DIR__ . "/test13pix.swf"));
$obj->setTest('test');
var_dump(json_decode('{"":"value"}', true));
set_exception_handler(function() {
    echo 'Fourth handler' . PHP_EOL;
});
var_dump($document->saveHTML());
odbc_exec($conn, "INSERT INTO bug80147 VALUES (1, CONVERT(VARBINARY(50), 'whatever'))");
$tester->terminate();
var_dump($foo);
ob_end_clean();
printf("# %s:\n", $name);
$t->test();
var_dump(yield from g());
var_dump(openssl_x509_checkpurpose($bert, X509_PURPOSE_ANY));
var_dump($dom->getElementById('x')?->nodeName);
printf("[%03d] Expecting '%s' got '%s'\n", $offset, $expected, $row['zero']);
php_cli_server_start(file_get_contents(__DIR__.'/bug64433_srv.inc'));
rewind($fp);
var_dump(gzfile(__DIR__."/data/test.txt.gz", true));
highlight_string($string, true);
var_dump($s);
var_dump((new Exception)->getTrace());
unlink($filename);
$val->dump();
mysqli_close($link);
var_dump($temp_array);
);
    var_dump($d == get_base;
$iterable->current();
var_dump($node->textContent == $text);
bar();
gzclose($h);
