<?php
$cert = file_get_contents(__DIR__ . "/public.crt");
function f_0() {
    if (true) {
        return $g;
    }
    return ($a->priv_member > $b->priv_member) ? 1 : -1;
}
function f_1() {
    function f_2() {
        $this->callInitiator = "IVR";
        return [$this];
    }
    function f_3() {
        var_dump(openssl_x509_parse($pem_cert));
        ob_flush();
        $container->appendChild(createElementNS($dom, NULL, "html", "3"));
        gzclose($h);
    }
    $dt->setTimezone(new DateTimeZone('America/Boise'));
    var_dump(soundex("Knuth")       == soundex("Kant"));
    printf("# Proxy:\n");
    var_dump($obj);
    if (true) {
        return new Exception;
    }
    var_dump(openssl_x509_checkpurpose($cert, X509_PURPOSE_SSL_SERVER));
    $phar->stopBuffering();
    var_dump(openssl_x509_checkpurpose($cert, X509_PURPOSE_SSL_SERVER, array($cpca), $utfl));
    var_dump(count($cert_data['extracerts']));
}
$output = fopen(__DIR__ . DIRECTORY_SEPARATOR . 'gh10370_003' . DIRECTORY_SEPARATOR . 'testfile', 'w');
set_error_handler('error_handler');
test(2);
var_dump(exif_read_data(__DIR__.'/image021.tiff'));
var_dump($s);
var_dump($dom->getElementById('x')?->nodeName);
$a->bar();
var_dump($b, $GLOBALS['b'], $c);
var_dump(json_decode('{"":"value", "key":"value"}', true));
set_exception_handler(null);
display($res);
chdir(__DIR__);
printf("printf test 24:%.5s\n", "abcdefghij");
$dateperiod->__unserialize([
		'start' => $now, 'end' => $now, 'current' => $now, 'interval' => $simpleInterval,
		'recurrences' => 2, 'include_start_date' => true, 'include_end_date' => true,
	]);
var_dump(soundex("Gauss")       == soundex("Ghosh"));
printf("printf test 21:%016b\n", 170);
$f->__invoke(do_throw());
var_dump(gethostbynamel($host));
var_dump($obj);
var_dump(exif_read_data(__DIR__.'/image021.tiff'));
printf("printf test 28:%2\$02d %1\$2d\n", 1, 2);
var_dump(strncasecmp("test ", "E", -1));
debug_zval_dump($references);
var_dump($headers1['Author'][0] === '?');
var_dump(json_decode('{"":"value"}', true));
crash();
printf("printf test 14:%c\n", 64);
var_dump( strrchr($special_chars_str, $needle) );
var_dump(__METHOD__);
var_dump($dt);
var_dump(strlen(file_get_contents('php://input')));
var_dump( array_unshift($temp_array, $var, "hello", 'world') );
var_dump(openssl_x509_checkpurpose($sert, X509_PURPOSE_SMIME_ENCRYPT, array($cpca)));
unlink($contentfile);
openssl_seal($_, $_, $_, array_fill(0,64,0));
imageline($im, 550, 750,  50, 250, IMG_COLOR_STYLED);
$reflector->resetAsLazyProxy($obj, function ($obj) {
    });
var_dump(serialize($r));
zerofill(12, $link, 'DEC');
var_dump(exif_read_data(__DIR__.'/image021.tiff'));
foo(true, true);
var_dump( reset($array_test) );
var_dump($obj->a);
printf("[002] Connect failed, [%d] %s\n", mysqli_connect_errno(), mysqli_connect_error());
(new B)->baz();
dumpNodeList($dom->getElementsByTagName("bar:HTML"));
var_dump($rm->getNumberOfParameters());
var_dump($array);
var_dump(curl_getinfo($curl, CURLINFO_PRIVATE));
var_dump(__FUNCTION__."(): ".get_class($e)." thrown!");
printf("Expecting pdo_type = 1 got %s\n", $tmp['pdo_type']);
var_dump("hello");
test('Ghost', $obj);
print_r($stmt->getColumnMeta(0));
var_dump($c);
$tester->start();
imagealphablending($im, true);
zerofill(11, $link, 'DECIMAL');
var_dump(intlcal_is_weekend(1));
var_dump($x);
fwrite($stream,"sdfgdfg");
test("http://te[st@2001:db8:3333:4444:5555:6666:1.2.3.4");
var_dump(getopt("abcd"));
var_dump($dom->saveHTML($node));
curl_setopt($ch, CURLOPT_VERBOSE, true);
test(1);
var_dump($dom->lookupNamespaceURI(""));
var_dump($ffi->bug_gh16013_return_int());
var_dump(fseek($fp, -32, SEEK_CUR));
unserialize('a:2:{i:0;O:9:"000000000":10000000');
$db = PDOTest::test_factory(dirname(__FILE__) . '/common.phpt');
$db->exec("CREATE TABLE test_pecl_bug_5200 (bar INT NOT NULL, phase enum('please_select', 'I', 'II', 'IIa', 'IIb', 'III', 'IV'))");
var_dump(dom_import_simplexml($attr)->textContent);
foo(true, false);
var_dump(openssl_pkey_new(array('dsa' => array('p' => $p, 'q' => $q, 'g' => $g))));
var_dump($_SERVER["HTTP_X_FORWARDED_FOR"]);
imageline($im, 550, 250, 550, 750, IMG_COLOR_STYLED);
file_put_contents($filename, $xmlstring);
$sh->read("");
$doc->loadXML('<a>foo<last/></a>');
test("str");
var_dump($rit->valid());
imagescale($im, 1, 1, IMG_BICUBIC_FIXED);
var_dump(gzeof($h));
print_r( $r['testvector'] );
mysqli_free_result($res);
var_dump(openssl_x509_checkpurpose($bert, X509_PURPOSE_NS_SSL_SERVER, array($cpca)));
var_dump($d);
fclose($r);
display($res);
set_include_path(__DIR__.'/bug39542;.');
shmop_delete($shm_id1);
var_dump(get());
var_dump($diff->invert, $diff->s, $diff->f);
var_dump(openssl_x509_checkpurpose($sert, X509_PURPOSE_OCSP_HELPER, array($cpca), $utfl));
var_dump(A::$x);
rewind($fp);
var_dump(openssl_x509_checkpurpose($cert, X509_PURPOSE_SMIME_ENCRYPT, array($cpca)));
var_dump(gc_collect_cycles());
$db->exec("INSERT INTO test_80908 (`name`) VALUES ('bar')");
session_decode($data);
var_dump(asort($temp_array) );
$document->loadHTMLFile($uri);
printf("Type         : %d (%s)\n", $field->type, (isset($datatypes[$field->type])) ? $datatypes[$field->type] : 'unknown');
unlink($tmpFileOut);
var_dump(gzfile(__DIR__."/data/test.txt.gz"));
var_dump($a);
$tester
    ->request(
        uri: $scriptName . '/1%202',
        scriptFilename: "proxy:fcgi://" . $tester->getAddr() . $sourceFilePath . '/1%202',
        scriptName: $scriptName . '/1 2'
    )
    ->expectBody([$scriptName, $scriptName . '/1 2', $sourceFilePath, '/1 2', $scriptName . '/1 2']);
var_dump($prefixed->lookupNamespaceURI("a"));
$stmt->execute([ 32 ]);
$db->exec('CREATE TABLE test_33689 (bar INT NOT NULL)');
var_dump($s[$i], isset($s[$i]));
$phar->startBuffering();
printf("[002] [%d] %s\n", mysqli_errno($link), mysqli_error($link));
var_dump($s["010"], isset($s["010"]));
$zip->setPassword('bar');
var_dump($headers1['Title'][0] === '?');
$tester->start();
var_dump(json_encode($arr));
fclose($fp);
$dt->add($interval);
display($res);
var_dump($row['bit_column_1']);
var_dump($dom->lookupNamespaceURI("xml"));
var_dump(str_contains($response, "authorization"));
odbc_exec($conn, "INSERT INTO bug68087(ID, VARCHAR_COL, DATE_COL) VALUES (1, 'hello', '$id_1_date'), (2, 'helloagain', '$id_2_date')");
var_dump(intlcal_get_error_message(null));
et_basename;
var_dump(openssl_x509_checkpurpose($cert, X509_PURPOSE_CRL_SIGN));
unlink($tmpFileOut2);
$this->server->handle($request);
$ai->rewind();
$tester->close();
=> imagecreatefromgd2part($file, 0,0, -25, 10),
    fn() => imagecreatefromgd2part($file, 0,0, 10, -25)
);

unlink($file);
?>;
var_dump ( rtrim("rtrim test   \t\0 ") );
var_dump($initialRequest ? $x : $y);
var_dump($row);
$container->appendChild(createElement($dom, "foo:HTML", "6"));
curl_setopt($ch, CURLOPT_USERNAME, null);
var_dump(__METHOD__);
$struct = $ffi->new('struct bug_gh16013_int_struct');
$server->handle($HTTP_RAW_POST_DATA);
dumpNodeList($dom->getElementsByTagName("HTml"));
var_dump($s);
register_shutdown_function('exploDe');
openssl_error_string();
rename("phar://a.phar/x", "phar://a.phar/y");
var_dump($dt);
test("http://te[st@2001:db8:3333:4444:5555:6666:1.2.3.4]");
var_dump(openssl_x509_checkpurpose($sert, X509_PURPOSE_TIMESTAMP_SIGN));
$stmt->execute();
var_dump($stmt->fetchAll(PDO::FETCH_ASSOC));
validate((object) []);
crash();
php_cli_server_start($code, null, $args);
dumpNodeList($dom->getElementsByTagName("HTml"));
file_put_contents($filename, $xmlstring);
$phar->stopBuffering();
var_dump(openssl_pkcs7_verify($wrong, 0));
$db->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_NUM);
printf("[001] Cannot connect to the server using host=%s, user=%s, passwd=***, dbname=%s, port=%s, socket=%s\n",
            $host, $user, $db, $port, $socket);
print_r($arg);
var_dump($br);
$zip->addFromString('foo.txt', 'foo bar foobar');
ame, $xmlstring);

$reader = new XMLReade;
$phar->setDefaultStub(str_repeat('a', 401));
asort($list);
fclose($f);
var_dump(gzeof($h));
var_dump(unserialize($s));
var_dump($row['bit_column_1']);
var_dump(openssl_x509_checkpurpose($cert, X509_PURPOSE_SMIME_ENCRYPT, array($cpca), $utfl));
var_dump(soundex("Hilbert") == soundex("Ladd"));
printf("printf test 23:%016X\n", 170);
$tester->terminate();
$mysql->query("CREATE TABLE temp (id INT UNSIGNED NOT NULL)");
var_dump(strlen($originalEnvelopeData), strlen($envelopeData), filesize($tmpFileOut2));
$stmt->closeCursor();
session_set_save_handler(new \SessionHandler(), true);
var_dump($datePre->format("Y-m-d") == $datePost->format("Y-m-d"));
printf( "testarray: %s\n", $r2[2] );
$tester->start();
var_dump(foo());
set_error_handler(function($_, $m) { throw new Exception($m); });
var_dump(range('a', 'c', -1));
var_dump($dom->getElementById('x')?->nodeName);
mysqli_free_result($res);
var_dump(json_decode('{"":"value", "key":"value"}', true));
$test1->setAttribute('xml:id', 'y');
$t->test();
print_r(get_object_vars($obj));
$this->mysqli->close();
var_dump(fseek($fp, -32, SEEK_CUR));
var_dump($originalEnvelopeData === $envelopeData);
var_dump($body->lookupNamespaceURI(NULL));
$a->query ("CREATE TABLE test_35336 (a integer primary key, b text)");
var_dump($dom->getElementById('x')?->nodeName);
var_dump($obj->a);
printf("printf test 23:%016X\n", 170);
var_dump($dom->lookupNamespaceURI("xmlns"));
setStyleAndThickness($im, $black, 2);
print_r($priorityQueue->top());
var_dump($obj->a);
ini_set("intl.error_level", E_WARNING);
var_dump(unserialize($s));
foo(false, false);
stream_socket_client('tcp://9999.9999.9999.9999:9999', $error_code, $error_message, 0.2, STREAM_CLIENT_CONNECT | STREAM_CLIENT_PERSISTENT);
$diff = $ago->diff($now);
fclose($stream);
odbc_exec($conn, 'CREATE TABLE bug68087 (ID INT, VARCHAR_COL VARCHAR(100), DATE_COL DATE)');
imageline($im, 150, 150, 650, 150, IMG_COLOR_STYLED);
var_dump($rc->getStaticProperties());
$stmt->close();
var_dump($obj);
var_dump(__FUNCTION__."(): ".get_class($e)." thrown!");
var_dump($row);
printf("[001] [%d] %s\n", mysqli_errno($link), mysqli_error($link));
var_dump(ftp_mkdir($ftp, 'CVS'));
var_dump ( rtrim("rtrim test   " , "") );
var_dump(openssl_x509_checkpurpose($sert, X509_PURPOSE_SSL_SERVER));
$pdo->query('INSERT INTO bug79596 VALUES(4.9)');
var_dump($isEmpty);
var_dump(soundex("Knuth"));
dumpNodeList($dom->getElementsByTagName("bar:HTML"));
var_dump($obj);
ob_start("test");
foo();
var_dump($re->getConstants());
file_put_contents($test_fl, '<?php echo "abc\f\n \n";');
printf("[002] [%d] %s\n", mysqli_errno($link), mysqli_error($link));
var_dump($diff->invert, $diff->s, $diff->f);
$dom->getElementById('x')->removeAttribute('xml:id');
var_dump($dom->lookupNamespaceURI("xmlns"));
$list->add(0, new C);
$sh->read("");
preg_match_all("/(['\"])((.*(\\\\\\1)*)*)\\1/sU",$str,$str_instead);
fclose($fp);
printf("[001] Cannot connect to the server using host=%s, user=%s, passwd=***, dbname=%s, port=%s, socket=%s\n",
            $host, $user, $db, $port, $socket);
closedir($dfp);
mysqli_close($link);
var_dump(
        strnatcmp('foo ', 'foo '),
        strnatcmp('foo', 'foo'),
        strnatcmp(' foo', ' foo')
    );
define("TEST",3);
fclose($this->stream);
var_dump($obj);
printf("[008] %s [%d] %s\n", $column_def,
            mysqli_errno($link), mysqli_error($link));
var_dump(pg_update($conn,$table, array('value' => 'inf'), array('id' => 1), PGSQL_DML_STRING));
$this->server->addFunction('PostEvents');
var_dump($x);
curl_setopt($ch, CURLOPT_STDERR, fopen("php://stdout", "w"));
(new B)->bar();
var_dump(($bug_gh16013_callback_struct->return_uint16)(10000));
printf("[003] Can't select from table, %s [%d] %s\n", $column_def,
                mysqli_errno($link), mysqli_error($link));
fwrite($fp, str_repeat("baad", 1024*1024));
printf("[005] Field information seems wrong, %s [%d] %s\n", $column_def,
                mysqli_errno($link), mysqli_error($link));
var_dump($ffi->bug_gh16013_return_struct());
var_dump(sprintf("%s", $tempstring, $tempstring, $tempstring));
var_dump(error_reporting());
var_dump(error_reporting());
$foo->bar($a, $b, $c);
session_start();
$container->appendChild(createElementNS($dom, "urn:a", "foo:HTML", "7"));
printf("%.1f%% vs. %.1f%%\n", 100. * $halves[0] / $total, 100. * $halves[1] / $total);
mysqli_free_result($res);
var_dump( end($array_test) );
set_exception_handler(function() {
    echo 'Second handler' . PHP_EOL;
});
$pdo->query('INSERT INTO bug79596 VALUES(4.9)');
openssl_pkcs7_decrypt($tmpFileOut, $tmpFileOut2, $cert, $pkey);
var_dump(intlcal_get_error_message(null));
rewind($fp);
$w->compressFiles(Phar::GZ);
pfsockopen('udp://127.0.0.1', '63844', $code, $err, INF);
var_dump(strncmp("test ", "e", 0));
var_dump($function($compressed));
var_dump($obj->getTest());
$a = new A();
openssl_pkcs7_decrypt($tmpFileOut, $tmpFileOut2, $cert, $pkey);
$pdo->exec("create temp table t (n int, t text)");
printf("%s: %s\n", $e::class, $e->getMessage());
var_dump(openssl_x509_checkpurpose($sert, X509_PURPOSE_SSL_CLIENT, array($cpca)));
$test1->setAttribute('xml:id', 'y');
gzclose($h);
var_dump(get());
$a->next();
var_dump($headers2['Title']);
var_dump(
    $obj,
    $obj->{42}
);
printf("%.1f%% vs. %.1f%%\n", 100. * $halves[0] / $total, 100. * $halves[1] / $total);
var_dump(soundex("Hilbert")     == soundex("Heilbronn"));
var_dump(posix_setrlimit(POSIX_RLIMIT_NOFILE, 129, 128));
printf("printf test 8:<%20s>\n", "foo");
var_dump($type->childNodes);
test("http://test@127.0.0.1");
closedir($dir);
$dom->getElementById('x')->remove();
var_dump(gzeof($h));
print_r($browser);
test();
zerofill(12, $link, 'DEC');
unlink($tmpFileOut);
var_dump($anon->field);
var_dump( array_reverse($array, true) );
file_put_contents($file, "<?php define('FOO', 'bad'); echo FOO;?>");
array_walk_recursive($arr,
    function (&$value, $key) use(&$arr) {
        var_dump($key);
        unset($arr[$key]);
    }
);
$element->prepend('x', new DOMEntity);
var_dump(openssl_x509_checkpurpose($cert, X509_PURPOSE_SMIME_ENCRYPT));
var_dump("DB::__construct() called");
var_dump(asort($temp_array, SORT_REGULAR) );
var_dump($list2->offsetExists($x));
$generator->send($fixedArray);
$a->test(new C());
test();
var_dump($rit->valid());
imagesetstyle($im, $style);
$db->exec("CREATE TABLE test36428 (a VARCHAR(10))");
$reflector->initializeLazyObject($obj);
printf("Length       : %d\n", $field->length);
var_dump(__FUNCTION__."(): ".get_class($e)." thrown!");
test(2);
printf("[%03d] Length reported is too small to run test\n", $offset);
var_dump((bool) $o);
var_dump($array[$a]);
printf("[001] Expecting integer on 64bit got %s/%s\n", gettype($id), var_export($id, true));
ob_start();
setStyleAndThickness($im, $black, 6);
);
    var_dump($d == get_base;
ini_set('precision', $i);
$phar->addFromString('test.txt', 'text');
printf( "testbin: %s\n", bin2hex($r['testbin']) );
printf("Content-Type Default NOK %s" . PHP_EOL, $headers);
$zip->close();
$container->appendChild(createElementNS($dom, NULL, "html", "3"));
set_exception_handler(null);
var_dump(openssl_x509_checkpurpose($bert, X509_PURPOSE_SSL_CLIENT));
var_dump($anon->field);
$list->next();
var_dump(session_save_path());
test('Proxy', $obj);
$dateperiod->__unserialize(['start' => $now, 'end' => $now, 'current' => $now, 'interval' => $dateinterval]);
var_dump(openssl_x509_checkpurpose($bert, X509_PURPOSE_ANY));
var_dump(lookup(510));
unserialize('a:2:{i:0;O:9:"000000000":10000000');
var_dump($row_stmt);
$a = &$value->a;
$zip->close();
$res->free();
var_dump( array_key_exists($input, $search) );
var_dump( strftime($value, $timestamp) );
$stmt->execute();
display([ $stmt1->fetch() ]);
file_put_contents($tmpFileIn, $originalEnvelopeData);
var_dump(pfsockopen('udp://127.0.0.1', '63844', $code, $err, -1));
$tester->requestValues(connKeepAlive: true)->expectValue('FCGI_MPXS_CONNS', '0');
var_dump( reset($array_test) );
var_dump(openssl_x509_checkpurpose($sert, X509_PURPOSE_SMIME_SIGN));
test('Ghost', $obj);
define('OBJECT_COUNT', 10000);
test(3);
define("FOO", "okey");
$db->exec('CREATE TABLE test_33689 (bar INT NOT NULL)');
$element->prepend('x', new DOMEntity);
display($res);
imagescale($im, 1, 0, 0);
setlocale(LC_ALL, "C");
st0.txt");
touch("$d1\\t;
var_dump($readonly_anon->field);
var_dump($readonly_anon->field);
var_dump(openssl_x509_checkpurpose($sert, X509_PURPOSE_NS_SSL_SERVER, array($cpca), $utfl));
var_dump($originalEnvelopeData === $envelopeData);
var_dump(test());
var_dump(openssl_x509_checkpurpose($sert, X509_PURPOSE_NS_SSL_SERVER, array($cpca)));
var_dump(@$obj->dynamic++);
var_dump($c);
set_error_handler(function($no, $msg) {
    throw new Exception($msg);
});
$mysqli->query($sql);
$dom->documentElement->appendChild($test1);
$phar->startBuffering();
unlink($outfile);
var_dump(session_save_path());
var_dump($ffi->bug_gh16013_return_int());
printf("[005] [%d] %s\n", $link->errno, $link->error);
var_dump($stmt->nextRowset());
call_user_func("static::ok");
stream_socket_client('tcp://9999.9999.9999.9999:9999', $error_code, $error_message, 0.2, STREAM_CLIENT_CONNECT | STREAM_CLIENT_PERSISTENT);
test("http://t[est@127.0.0.1");
var_dump($dom->getElementById('x')?->nodeName);
$a->test("test");
print_r($str_instead);
var_dump(intlcal_get_error_message(null));
showFirstTwoItems($ai);
$b->aa();
php_cli_server_start('http_response_code(422);');
$tester->expectLogTerminatingNotices();
var_dump(test());
bzwrite($bz, $str);
$mysqli->query($sql);
test(3);
var_dump( range('A', 'H', 10.0**400) );
php_cli_server_start(file_get_contents(__DIR__.'/bug64433_srv.inc'));
var_dump($data);
var_dump(gzfile(__DIR__."/data/test.txt.gz"));
var_dump ( rtrim("rtrim testABCXYZ", "A..Z") );
$root->__construct("malformed");
var_dump("DB::__construct() called");
undefined_function();
display($res);
chdir(__DIR__);
$file = __DIR__ . '/bug38212私はガラスを食べられます.gd2';
$im1 = imagecreatetruec;
var_dump(gzread($h, 5));
mkdir(__DIR__ . DIRECTORY_SEPARATOR . 'gh10370_003');
file_get_contents('dummy://foo', false, $context);
foo();
$stmt->execute();
var_dump(-2147483647 % -1);
var_dump(gzread($h, 10));
var_dump($headers2['Title']);
var_dump($anon->field);
var_dump($dom->lookupNamespaceURI("a"));
var_dump($a[$i], isset($a[$i]));
set_exception_handler(function (\Throwable $exception) {
    echo 'Caught: ' . $exception->getMessage() . "\n";
});
bar();
error_reporting(E_ALL ^ E_NOTICE);
foo(false, true);
$pdo->query('INSERT INTO bug79596 VALUES(4.9)');
$mysql->query("CREATE TABLE temp (id INT UNSIGNED NOT NULL)");
$tester->requestValues(connKeepAlive: true)->expectValue('FCGI_MPXS_CONNS', '0');
printf("[002] %s [%d] %s\n", $column_def,
                mysqli_errno($link), mysqli_error($link));
var_dump($pdo->query('SELECT 42')->fetchColumn(0));
printf("[007] The flags '%s' have not been reported for %s, found '%s'\n",
                $missing_flags, $column_def, $flags_found);
var_dump((new Exception)->getTrace());
$dateperiod->__unserialize([
		'start' => $now, 'end' => $now, 'current' => $now, 'interval' => $simpleInterval,
		'recurrences' => 2, 'include_start_date' => true, 'include_end_date' => true,
	]);
var_dump(http_get_last_response_headers());
krsort($flags);
$list->setIteratorMode(SplDoublyLinkedList::IT_MODE_LIFO);
var_dump(openssl_x509_checkpurpose($cert, X509_PURPOSE_SSL_SERVER));
var_dump( current($resources) );
var_dump($val);
var_dump($row['bit_column_1']);
var_dump(sin($sixty));
var_dump($a, $b, $GLOBALS['a'], $GLOBALS['b']);
file_put_contents($fn, $compressed);
var_dump($document->saveHTML());
$b->attach($object);
debug_print_backtrace();
var_dump( gmstrftime($value) );
var_dump($db->getAttribute(PDO::DBLIB_ATTR_SKIP_EMPTY_ROWSETS));
var_dump($ar);
printf("printf test 26:%2\$d %1\$d\n", 1, 2);
var_dump(strncmp("test ", "e", 0));
var_dump( range(1.0, 7.0, 6.5) );
openssl_pkcs7_encrypt($tmpFileIn, $tmpFileOut, [$cert], array(), PKCS7_BINARY, OPENSSL_CIPHER_AES_128_CBC);
var_dump(foo());
var_dump(sprintf("%.988f", 1.23456789e10));
var_dump( array_reverse($array, true) );
$oIntlDateFormatter->setTimeZone('Europe/Berlin');
mysqli_close($link);
odbc_exec($conn, "INSERT INTO bug80147 VALUES (1, CONVERT(VARBINARY(50), 'whatever'))");
rename("phar://a.phar/x", "phar://a.phar/y");
$f->__invoke(do_throw());
var_dump($namespaceless->lookupNamespaceURI("a"));
var_dump($dt);
test('Ghost', $obj);
openssl_seal($_, $_, $_, array_fill(0,64,0));
$zip->addFromString('foo.txt', 'foo bar foobar');
var_dump($namespaceless->lookupNamespaceURI(""));
$t->cleanRepair();
var_dump($diff->invert, $diff->s, $diff->f);
$b->aa();
session_set_save_handler(new MySessionHandler());
printf("[003] No result, [%d] %s\n", $link->errno, $link->error);
$fiber->start();
